#!/bin/bash

EXEC_DIRECTORY=`dirname $0`
pushd $EXEC_DIRECTORY

if [ -n "$DEBUG" ]; then
    LD_LIBRARY_PATH=. gdb --args Client --network.port 1234 --network.address localhost $@
elif [ -n "$VALGRIND" ]; then
    echo "Executing with Vagrind"
    LD_LIBRARY_PATH=. valgrind --leak-check=full ./Client --network.port 1234 --network.address localhost $@
else
    LD_LIBRARY_PATH=. ./Client --network.port 1234 --network.address localhost $@
fi

xset r on

popd

