#!/bin/bash

EXEC_DIRECTORY=`dirname $0`
pushd $EXEC_DIRECTORY

_LD_LIBRARY_PATH=$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

client=Client
if [ -f Client.exe ]; then
    client=Client.exe
fi

if [ -n "$DEBUG" ]; then
    echo "executing with gdb"
    gdb --args Client --network.port 1234 --network.address localhost $@
elif [ -n "$VALGRIND" ]; then
    echo "executing with vagrind"
    valgrind --leak-check=full ./Client --network.port 1234 --network.address localhost $@
elif [ -n "$WINE" ]; then
    wine ./$client --network.port 1234 --network.address localhost $@
else
    ./$client --network.port 1234 --network.address localhost $@
fi

xset r on

popd

