#! /usr/bin/env python

import sys
from xml.dom import minidom

messagesHpp = open("Messages/UnitTests/MessagesTest.cpp", "w")
messages = minidom.parse('Messages/Messages.xml')

def genHeader():
	messagesHpp.write(
		"/* this file is autogenerated, do not edit! */\n\n"
		"#include <cppunit/TestFixture.h>\n"
		"#include <cppunit/extensions/HelperMacros.h>\n\n"
		"#include <iostream>\n\n"
        "#include \"Common/Logger/Logger.hpp\"\n"
		"#include <RustedCodec/SimpleWriteBuffer.hpp>\n"
		"#include <RustedCodec/SimpleReadBuffer.hpp>\n\n"
		"#include <Messages/Messages.hpp>\n\n"
		"class MessagesTest : public CPPUNIT_NS::TestFixture\n"
		"{\n"
		"\tCPPUNIT_TEST_SUITE (MessagesTest);\n"
	)

	for message in messages.childNodes[0].getElementsByTagName("message"):
		messagesHpp.write("\tCPPUNIT_TEST (testMessage_" + message.getAttribute("id") + ");\n")

	messagesHpp.write(
		"\tCPPUNIT_TEST_SUITE_END ();\n\n"
		"protected:\n"
	)

	for message in messages.childNodes[0].getElementsByTagName("message"):
		messagesHpp.write("\tvoid testMessage_" + message.getAttribute("id") + "();\n")

	messagesHpp.write(
		"};\n"
		"CPPUNIT_TEST_SUITE_REGISTRATION (MessagesTest);\n\n"
	)

def genTests():
	for message in messages.childNodes[0].getElementsByTagName("message"):
		messagesHpp.write(
			"void MessagesTest::testMessage_" + message.getAttribute("id") + "()\n"
			"{\n"
			"\tusing ::Common::RustedCodec::SimpleWriteBuffer;\n"
			"\tusing ::Common::RustedCodec::SimpleReadBuffer;\n"
			"\tusing ::Common::Messages::AbstractMessage;\n"
			"\tusing ::Common::Messages::" + message.getAttribute("id") + ";\n\n"
			"\t" + message.getAttribute("id") + " inMessage;\n"
		)

		for param in message.getElementsByTagName("param"):
			messagesHpp.write("\t")
			if param.getAttribute("type") == "boolean":
				messagesHpp.write("inMessage." + param.getAttribute("name") + " = true;\n")
			elif param.getAttribute("type") == "string":
				messagesHpp.write("inMessage." + param.getAttribute("name") + " = \"some test string\";\n")
			elif param.getAttribute("type") == "int32":
				messagesHpp.write("inMessage." + param.getAttribute("name") + " = 0xf00d;\n")
			else:
				print "unknown param type: " + param.getAttribute("type") + "!"
				sys.exit(1)

		messagesHpp.write(
			"\n"
			"\tstd::vector<char> raw_buf;\n"
			"\tSimpleWriteBuffer buf(raw_buf);\n"
			"\tinMessage.serialize(buf);\n\n"
			"\tSimpleReadBuffer read_buf(raw_buf);\n"
			"\tstd::auto_ptr<AbstractMessage> outMessage = ::Common::Messages::MessageFactory::create(read_buf);\n\n"
			"\tCPPUNIT_ASSERT(0 != dynamic_cast<" + message.getAttribute("id") + " *>(outMessage.get()));\n"
			"\tCPPUNIT_ASSERT_EQUAL(::Common::Messages::Id::" + message.getAttribute("id") + ", outMessage->getId());\n"
		)

		messagesHpp.write(
			"\tLOG_INFO << *dynamic_cast<" + message.getAttribute("id") + " *>(outMessage.get());\n")

		for param in message.getElementsByTagName("param"):
			messagesHpp.write(
				"\tCPPUNIT_ASSERT(inMessage." + param.getAttribute("name") + " == dynamic_cast<" + message.getAttribute("id") +
				" *>(outMessage.get())->" + param.getAttribute("name") + ");\n"
			)

		messagesHpp.write(
			"}\n\n"
		)

genHeader()
genTests()

print "Messages/UnitTests/MessagesTest.cpp written"

